name: discordBotSpigotCommunication
version: 1.19.2

main: discord.bot.spigot.communication.wise_mystical_tree

commands: {
  send: {
    description: "send a message to the server",
    usage: "/send <message>",
    permission: "wise.send"
  },
  connect: {
    description: "try to connect to discord bot",
    usage: "/connect",
    permission: "wise.connect"
  }
  permissions: {
    wise.send: {
      description: "allows user to send a message to the discord chat",
      default: true
    }
    wise.connect: {
      description: "allows user to try and connect to the discord bot",
      default: "op"
    }
  }
}
